// <auto-generated />
using System;
using HotelBooking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelBooking.Data.Migrations
{
    [DbContext(typeof(HotelBookingDbContext))]
    [Migration("20220728231621_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("HotelBooking.Entities.Booking", b =>
                {
                    b.Property<Guid>("BookingRef")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("NoOfGuests")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("TEXT");

                    b.HasKey("BookingRef");

                    b.HasIndex("RoomId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("HotelBooking.Entities.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Holiday Inn"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Novotel"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Premier Inn"
                        });
                });

            modelBuilder.Entity("HotelBooking.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HotelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HotelId = 1,
                            RoomTypeId = 1,
                            Title = "Room 101"
                        },
                        new
                        {
                            Id = 2,
                            HotelId = 1,
                            RoomTypeId = 2,
                            Title = "Room 102"
                        },
                        new
                        {
                            Id = 3,
                            HotelId = 1,
                            RoomTypeId = 3,
                            Title = "Room 103"
                        },
                        new
                        {
                            Id = 4,
                            HotelId = 1,
                            RoomTypeId = 1,
                            Title = "Room 201"
                        },
                        new
                        {
                            Id = 5,
                            HotelId = 1,
                            RoomTypeId = 2,
                            Title = "Room 202"
                        },
                        new
                        {
                            Id = 6,
                            HotelId = 1,
                            RoomTypeId = 3,
                            Title = "Room 203"
                        },
                        new
                        {
                            Id = 7,
                            HotelId = 2,
                            RoomTypeId = 1,
                            Title = "Room 101"
                        },
                        new
                        {
                            Id = 8,
                            HotelId = 2,
                            RoomTypeId = 2,
                            Title = "Room 102"
                        },
                        new
                        {
                            Id = 9,
                            HotelId = 2,
                            RoomTypeId = 3,
                            Title = "Room 103"
                        },
                        new
                        {
                            Id = 10,
                            HotelId = 2,
                            RoomTypeId = 1,
                            Title = "Room 201"
                        },
                        new
                        {
                            Id = 11,
                            HotelId = 2,
                            RoomTypeId = 2,
                            Title = "Room 202"
                        },
                        new
                        {
                            Id = 12,
                            HotelId = 2,
                            RoomTypeId = 3,
                            Title = "Room 203"
                        },
                        new
                        {
                            Id = 13,
                            HotelId = 3,
                            RoomTypeId = 1,
                            Title = "Room 101"
                        },
                        new
                        {
                            Id = 14,
                            HotelId = 3,
                            RoomTypeId = 2,
                            Title = "Room 102"
                        },
                        new
                        {
                            Id = 15,
                            HotelId = 3,
                            RoomTypeId = 3,
                            Title = "Room 103"
                        },
                        new
                        {
                            Id = 16,
                            HotelId = 3,
                            RoomTypeId = 1,
                            Title = "Room 201"
                        },
                        new
                        {
                            Id = 17,
                            HotelId = 3,
                            RoomTypeId = 2,
                            Title = "Room 202"
                        },
                        new
                        {
                            Id = 18,
                            HotelId = 3,
                            RoomTypeId = 3,
                            Title = "Room 203"
                        });
                });

            modelBuilder.Entity("HotelBooking.Entities.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 2,
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 3,
                            Type = 3
                        });
                });

            modelBuilder.Entity("HotelBooking.Entities.Booking", b =>
                {
                    b.HasOne("HotelBooking.Entities.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HotelBooking.Entities.Room", b =>
                {
                    b.HasOne("HotelBooking.Entities.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelBooking.Entities.RoomType", "RoomType")
                        .WithMany()
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("HotelBooking.Entities.Hotel", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("HotelBooking.Entities.Room", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
